### ISSUE TITLE
下载打印按钮

### ISSUE THREAD

**Issue by Boyka-SS** [zonemeen/react-tooling-kit#1]
请问您是如何，弄得那个框架，就是有打印和下载的那个灰色框架

**Comment by zonemeen** [comment]
> 请问您是如何，弄得那个框架，就是有打印和下载的那个灰色框架

你好，这个是iframe的默认带有的

**Comment by Boyka-SS** [comment]
好的好的，嘻嘻




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 中午1:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [miqilin21/react-file-preview] 下载打印按钮 (Issue #1)





  
请问您是如何，弄得那个框架，就是有打印和下载的那个灰色框架
  
你好，这个是iframe的默认带有的
