### ISSUE TITLE
项目启动后访问不了呀，我拉取的是master 分支

### ISSUE THREAD

**Issue by xingwendenggithub** [zonemeen/react-tooling-kit#2]
项目启动后访问不了呀，我拉取的是master 分支

**Comment by zonemeen** [comment]
> 项目启动后访问不了呀，我拉取的是master 分支
这个项目只有一个main分支呀 我启动后是好的 你拉一下最新的代码看看

**Comment by zonemeen** [comment]
> 项目启动后访问不了呀，我拉取的是master 分支

这个项目只有一个main分支呀 我启动后是好的 你拉一下最新的代码看看
